nodeLinker: node-modules

packageExtensions:
  eslint-plugin-flowtype@*:
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true

yarnPath: .yarn/releases/yarn-3.4.1.cjs
